### ISSUE TITLE
Git import

### ISSUE THREAD

**Issue by HenningCash** [code-freak/code-freak#112]
GitLab, BitBucket

**Comment by erikhofer** [comment]
https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CreateArchive.java

**Comment by HenningCash** [comment]
The first Git integration should be a simple "Import from Git" button, that behaves similar to the manual answer upload button: An input appears, that allows pasting a Git URL. The import is running only once and will override the current answer. A later full-featured integration could utilize web-hooks to do automated syncs and keep the Code FREAK answer up2date.

The CF admin has to configure a SSH deployment-key for each possible import-URL/-location.
