### ISSUE TITLE
Simple authentication: after logging out, you cannot log in a second time

### ISSUE THREAD

**Issue by erikhofer** [code-freak/code-freak#123]
This is not really relevant now because it only affects `dev` mode. We need to see if this problem persists after #122 is implemented.

**Comment by erikhofer** [comment]
The same error also prevents you from logging in with the same user in different browsers.

**Comment by HenningCash** [comment]
`AbstractUserDetailsAuthenticationProvider` is caching the `AppUser` after login but `ProviderManager` is calling `eraseCredentials` on the `AppUser` which is setting the `password` field to `null`.

It is possible to configure this behavior using the `AuthenticationManagerBuilder` but this made no difference for me:

```kotlin
  override fun configure(auth: AuthenticationManagerBuilder?) {
    when (config.authenticationMethod) {
      AuthenticationMethod.LDAP -> configureLdapAuthentication(auth)
      else -> super.configure(auth?.eraseCredentials(false))
    }
  }
```

**Comment by HenningCash** [comment]
Actually, there is no caching done by the `AbstractUserDetailsAuthenticationProvider`.
The `DevUserDetailsService` must return a new instance for every login of the same user. Otherwise the credentials of the in-memory instance from `SeedDatabaseService` will be erased.
