### ISSUE TITLE
Handle manual answer upload if IDE is running

### ISSUE THREAD

**Issue by HenningCash** [code-freak/code-freak#143]
Currently, if the online IDE is running and I am uploading some files manually the files will saved into database but the files from IDE will override the upload after some time without any further warning.

I see some possible solutions:
* Disable manual upload if IDE is running and tell student to use the IDE to drag & drop files for upload.
* Restart IDE with manual uploaded files (may need a full IDE reload and not only a server restart)
* Allow manual upload but stop & delete running IDE instance without save. Warn student before doing so!

**Comment by erikhofer** [comment]
fixed by #145?

**Comment by HenningCash** [comment]
:+1:
