### ISSUE TITLE
Test coverage report doesn't work correctly

### ISSUE THREAD

**Issue by erikhofer** [code-freak/code-freak#57]
E.g. `ContainerService` shows no coverage although there are tests for it.

![grafik](https://user-images.githubusercontent.com/17194301/57145095-c5bb9a00-6dc2-11e9-8afc-f5317dcd8fb5.png)

Gradle task output indicates some sort of error. 

```
λ gradlew jacocoTestReport

> Task :jacocoTestReport
[ant:jacocoReport] Classes in bundle 'code-freak' do no match with execution data. For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class de/code_freak/codefreak/service/ContainerService does not match.
[ant:jacocoReport] Execution data for class de/code_freak/codefreak/CodeFreakApplication does not match.
[ant:jacocoReport] Execution data for class de/code_freak/codefreak/config/DockerConfiguration does not match.
```

**Comment by HenningCash** [comment]
Works on Linux. Maybe a Windows problem?

![image](https://user-images.githubusercontent.com/2829004/57230168-02340380-7018-11e9-9b21-caf277956414.png)

**Comment by erikhofer** [comment]
Probably. The error message is related to this: https://stackoverflow.com/a/31916686/5519485
I guess as long as it works on CI we can ignore this?

**Comment by HenningCash** [comment]
Yep :+1:
