### ISSUE TITLE
Include Docker build in CI

### ISSUE THREAD

**Issue by erikhofer** [code-freak/code-freak#6]
Make sure that a PR cannot be merged if it breaks the Docker build. Either
* execute Docker build on Travis, or
* add another GitHub check for Docker

**Comment by HenningCash** [comment]
Docker Cloud has support for Testing on "Internal an External Pull Requests". This sounds like another check on GitHub. We should try this first and if it does not work switch to `docker build` on Travis.

**Comment by HenningCash** [comment]
Okay this works as expected in #7 but there is no "running" status for the check. It only reports success or failure after finishing on Docker Cloud and I am not sure if others can see the build log. Might be easier to run a `docker build` on Travis.

**Comment by HenningCash** [comment]
We will be using Docker Cloud checks for now and will switch to Travis CI based builds when tests require a docker daemon.
